
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: Client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"